# Generated by Django 5.1.4 on 2025-01-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_shared_post_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('😂', 'Laugh'), ('😲', 'Surprised'), ('😡', 'Angry'), ('👏', 'Clap'), ('🔥', 'Fire'), ('💯', '100'), ('🚀', 'Rocket'), ('👀', 'Eyes'), ('🙌', 'Praise'), ('🤔', 'Thinking'), ('👎', 'Thumbs Down'), ('🙏', 'Pray'), ('🎉', 'Celebrate'), ('🎵', 'Music'), ('🎨', 'Art'), ('📚', 'Books'), ('💡', 'Lightbulb'), ('🔗', 'Link'), ('📸', 'Camera'), ('🎥', 'Video'), ('🔒', 'Lock')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
