# Generated by Django 5.1.4 on 2025-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('👍', 'Thumbs Up'), ('😂', 'Laugh'), ('🔥', 'Fire'), ('👏', 'Clap'), ('🚀', 'Rocket')], max_length=2),
        ),
    ]
