# Generated by Django 5.1.4 on 2025-01-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0010_post_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="telegraph_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
