# Generated by Django 5.1.4 on 2025-01-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0011_postimage_telegraph_url_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="telegraph_url",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
    ]
