# Generated by Django 5.1.4 on 2025-01-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0012_remove_postimage_telegraph_url_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="telegraph_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
