# Generated by Django 5.1.4 on 2025-01-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0014_remove_postimage_telegraph_url_postimage_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="postimage",
            name="telegraph_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
