# Generated by Django 5.1.4 on 2025-01-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0015_remove_postimage_image_url_postimage_telegraph_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="telegraph_url",
        ),
    ]
