# Generated by Django 5.1.4 on 2025-01-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_reply_to_profile_shared_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shared_post',
        ),
    ]
