# Generated by Django 5.1.4 on 2025-01-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_profile_reply_to_remove_profile_shared_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegraph_profile_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
