# Generated by Django 5.1.4 on 2025-01-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_telegraph_profile_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="telegraph_profile_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
