# Generated by Django 5.1.4 on 2025-01-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_profile_profile_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="telegraph_profile_url",
        ),
    ]
