# Generated by Django 5.1.4 on 2025-01-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_profile_last_post_time_alter_profile_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
