# Generated by Django 5.1.5 on 2025-01-21 16:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_profile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default=accounts.models.get_default_profile_image,
                null=True,
                upload_to=accounts.models.profile_image_upload_path,
            ),
        ),
    ]
