# Generated by Django 5.1.5 on 2025-01-22 06:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="userapitoken",
            name="openrouter_token",
        ),
        migrations.AddField(
            model_name="aimodel",
            name="max_tokens",
            field=models.IntegerField(default=4096),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="system_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="temperature",
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name="userapitoken",
            name="google_gemini_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userapitoken",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userapitoken",
            name="last_reset_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userapitoken",
            name="monthly_token_usage",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_message_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "ai_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aichat.aimodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_user", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("error", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="aichat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
