# Generated by Django 5.1.5 on 2025-01-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0002_alter_aimodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="generation_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("gemini-pro", "Gemini Pro"),
                    ("gemini-pro-vision", "Gemini Pro Vision"),
                ],
                default="gemini-pro",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="safety_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
