# Generated by Django 5.1.5 on 2025-01-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0003_aimodel_generation_config_aimodel_model_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="generation_config",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="max_tokens",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="temperature",
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("gemini-1.5-pro", "Gemini Flash 2.0"),
                    ("gemini-1.5-pro-vision", "Gemini Flash 2.0 Vision"),
                ],
                default="gemini-1.5-pro",
                max_length=100,
            ),
        ),
    ]
