# Generated by Django 5.1.6 on 2025-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("repost", "Repost"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                ],
                max_length=20,
            ),
        ),
    ]
